std = {
   read_globals = {
        "Color",
        "GetConVar",
        "hook",
        "render",
        "vgui",
        "g_ContextMenu",
        "debug",
        "input",
        "MOUSE_LEFT",
        "KEY_E",
        "LocalPlayer",
        "util",
        "print",
        "math",
        "surface",
        "cam",
        "gui",
        "SysTime",
        "Vector",
        "IsValid",
        "unpack",
        "draw",
        "string",
        "TEXT_ALIGN_CENTER",
        "Angle",
        "tonumber",
        "vector_origin",
        "angle_zero",
    }
}
ignore = {"611"}
